apiVersion: v1
kind: Service
metadata:
  name: grafana 
  namespace: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  loadBalancerIP: 192.168.4.156