---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-local-data-pvc
  namespace: actual
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8192Mi # 8.1 GB