---
- name: Setup embeddev server
  hosts: embeddev
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Install Packages
      ansible.builtin.apt:
        name:
          - "git"
          - "build-essential"
          - "make"
          - "tio"
        state: "latest"

    - name: Get Arduino CLI
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh"
        dest: "/tmp/arduino-cli-install.sh"
        mode: 755

    - name: Install Arduino CLI
      ansible.builtin.shell:
        cmd: "bash /tmp/arduino-cli-install.sh"
      environment:
        BINDIR: /usr/local/bin

    - name: Install ESP Core
      ansible.builtin.shell:
        cmd: "arduino-cli core install esp32:esp32  --additional-urls=https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json"

    - name: Install MiniCore Core
      ansible.builtin.shell:
        cmd: "arduino-cli core install MiniCore:avr --additional-urls https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json"