---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-local-data-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi