apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        imagePullPolicy: Always
        image: homeassistant/home-assistant:latest
        volumeMounts:
          - name: home-assistant-local-data-volume
            mountPath: "/config"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2048Mi
            cpu: "2048"
          requests:
            memory: 1024Mi
            cpu: "1024m"
      volumes:
        - name: home-assistant-local-data-volume
          persistentVolumeClaim:
            claimName: home-assistant-local-data-pvc