---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-local-data-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi