apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
  type: LoadBalancer
