apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-homelab-kevin-lutzer-ca-tls
  namespace: longhorn-system
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kevinlutzer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - longhorn.homelab.kevin.lutzer.ca
  secretName: longhorn-homelab-kevin-lutzer-ca-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
