network:
  ethernets:
    eno1:
      dhcp4: true
      addresses: [192.168.4.200/24]
      nameservers:
        addresses: [1.1.1.1,8.8.8.8,192.168.4.1]
      routes:
        - to: default
          via: 192.168.4.1
  version: 2
  wifis: {}