---
- name: Prepare nodes for k3s install
  hosts: k3snodes
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: true

    - name: Install CSI for Longhorn
      ansible.builtin.apt:
        name: "open-iscsi"
        state: "latest"

    - name: Disable SWAP
      ansible.builtin.shell:
        cmd: "sudo dphys-swapfile swapoff"

    - name: Update Swap Size to 8GB
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^(CONF_SWAPSIZE=100)$' # by default for the newest rasp
        line: 'CONF_SWAPSIZE=8192'

    - name: Enable SWAP
      ansible.builtin.shell:
        cmd: "sudo dphys-swapfile swapon"

    - name: Activating cgroup support
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
        backrefs: true
      changed_when: false

    - name: Rebooting
      ansible.builtin.reboot:
      changed_when: false
