---
- name: Prepare nodes for k3s install
  hosts: k3smaster,k3snodes
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Install Packages
      ansible.builtin.apt:
        name:
          - "nfs-common"
          - "open-iscsi"
          - "util-linux"
        state: "latest"

    - name: Rebooting
      ansible.builtin.reboot:
      changed_when: false

    - name: Add longhorn system group
      group:
        name: longhorn
        state: present