---
- name: Install K3S For the Master Node
  hosts: k3smaster
  tasks:
    - name: CURL the K3S bin
      ansible.builtin.get_url:
        url: "https://get.k3s.io"
        dest: "/tmp/k3s"
        mode: 755

    - name: Install K3S
      ansible.builtin.shell:
        cmd: "bash /tmp/k3s"
      environment:
        INSTALL_K3S_EXEC: "--disable=servicelb,traefik"
        K3S_KUBECONFIG_MODE: "644"