---

- name: Raspian apt-get update && apt-get upgrade
  hosts: k3snodes,k3smaster
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: true
