apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld-kevinlutzer-ca-tls
  namespace: hello-world
spec:
  # Secret names are always required.
  secretName: helloworld-kevinlutzer-ca-tls
  duration: 168h # 1w
  renewBefore: 144h # 6d
  subject:
    organizations:
      - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: helloworld.homelab.kevinlutzer.ca
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - helloworld.homelab.kevinlutzer.ca
    - www.helloworld.homelab.kevinlutzer.ca
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.