apiVersion: v1
kind: Service
metadata:
  namespace: hello-world
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80