---
# This node runs ubuntu 23.04 LTS
- name: Setup the node that runs my personal website
  hosts: personalwebsite
  tasks:
    - name: Upgrade the OS and Install Docker
      ansible.builtin.apt:
        # upgrade: dist
        name:
          - "docker"
        state: "latest"
        update_cache: true

    # - name: Disable SWAP
    #   ansible.builtin.shell:
    #     cmd: "sudo dphys-swapfile swapoff"

    # - name: Update Swap Size to 4GB
    #   ansible.builtin.lineinfile:
    #     path: /etc/dphys-swapfile
    #     regexp: '^(CONF_SWAPSIZE=100)$' # by default for the newest rasp
    #     line: 'CONF_SWAPSIZE=4096'

    # - name: Enable SWAP
    #   ansible.builtin.shell:
    #     cmd: "sudo dphys-swapfile swapon"