apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planka-ingress
  namespace: planka
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - planka.homelab.kevin.lutzer.ca
    secretName: planka-homelab-kevin-lutzer-ca-tls
  rules:
  - host: planka.homelab.kevin.lutzer.ca
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: planka
              port:
                number: 80
                