---
apiVersion: v1
kind: Service
metadata:
  namespace: ipfinder
  name: ipfinder
spec:
  type: ClusterIP
  selector:
    app: ipfinder
  ports:
    - name: ipfinder
      port: 80
      targetPort: 80
      protocol: TCP
