apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  namespace: personal-website
spec:
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: personal-website
        imagePullPolicy: Always
        image: klutzer/personal-website:4.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: '8080'
        - name: DB_HOST
          value: '192.168.4.157'
        - name: DB_NAME
          value: 'personalwebsite'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbpassword
              name: personal-website-secret
        - name: DB_USER
          value: 'personalwebsite'
        - name: PING_HOST
          valueFrom:
            secretKeyRef:
              key: pinguri
              name: personal-website-secret
        - name: VERSION
          value: '4.1.0'