apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus-server
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30083 
  type: LoadBalancer