apiVersion: v1
kind: Service
metadata:
  namespace: speed-test
  name: speed-test
spec:
  selector:
    app: speed-test
  ports:
    - protocol: TCP
      port: 9798
      targetPort: 9798
  type: LoadBalancer
  loadBalancerIP: 192.168.4.158