---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-local-data-pvc
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi