apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: heimdall
  name: heimdall
  labels:
    app: heimdall
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        imagePullPolicy: Always
        image: lscr.io/linuxserver/heimdall:latest
        env:
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: "128m"
          requests:
            memory: 64Mi
            cpu: "64m"