apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall-kevinlutzer-ca-tls
  namespace: heimdall
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kevinlutzer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - heimdall.homelab.kevinlutzer.ca
  secretName: heimdall-kevinlutzer-ca-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
