apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: heimdall
  name: heimdall
  labels:
    app: heimdall
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 1
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
      - name: heimdall-pvc
        persistentVolumeClaim:
          claimName: heimdall-local-data-pvc
      containers:
      - name: heimdall
        imagePullPolicy: Always
        image: lscr.io/linuxserver/heimdall:latest
        env:
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "512m"
          requests:
            memory: 256Mi
            cpu: "256m"
        volumeMounts:                      
         - mountPath: /config              
           name: heimdall-pvc
           subPath: config