---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  namespace: heimdall
  name: heimdall-frontend
spec:
  selector:
    app: heimdall
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80