apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
  namespace: test-postgres # Set the name of the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.1-alpine3.19
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 2048Mi
              cpu: 2048m
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          env: 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-config # Using the ConfigMap postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              subPath: postgresdata
              readOnly: false
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: test-postgres-local-data-pvc