apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: n8n
  name: n8n
  labels:
    app: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: n8n
        imagePullPolicy: IfNotPresent
        image: docker.n8n.io/n8nio/n8n:latest
        env:
          - name: N8N_HOST
            value: n8n.homelab.kevinlutzer.ca
          - name: N8N_PORT
            value: "5678"
          - name: N8N_PROTOCOL
            value: https
          - name: NODE_ENV
            value: production
          - name: WEBHOOK_URL
            value: https://n8n.homelab.kevinlutzer.ca/
        volumeMounts:
          - name: n8n-local-data-volume
            mountPath: "/home/node/.n8n"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 4096Mi
            cpu: "4096m"
          requests:
            memory: 2048Mi
            cpu: "2048m"
      volumes:
        - name: n8n-local-data-volume
          persistentVolumeClaim:
            claimName: n8n-local-data-pvc