apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - n8n.homelab.kevin.lutzer.ca
    secretName: n8n-homelab-kevin-lutzer-ca-tls
  rules:
  - host: n8n.homelab.kevin.lutzer.ca
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: n8n
              port:
                number: 80
