# Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.homelab.kevin.lutzer.ca"
    upstream-base-url: "https://ntfy.sh"
    log-level: debug