---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-local-data-pvc
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi